### ISSUE TITLE
pmix_mca_base_var_cache_files multiple invocations

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/master#194]
I noted pmix_mca_base_var_cache_files is invoked both in pmix_mca_base_var_init and pmix_rte_init.

Is there any rationale for that ?
Even if it might not harm, this seems to indirectly leak some memory

**Comment by rhc54** [comment]
No, we shouldn't be doing that - I would just let base_var_init handle it.

Likewise, your other question about libevent global shutdown was also valid, but needs to go one step further - we should never call that function, not even from within OMPI. For example, if the application is using libevent for its own purposes, or another library in the app is doing so, we could shut it down for everyone. So that should simply be eliminated.

Do you want to handle these? Or shall I do so?

**Comment by ggouaillardet** [comment]
@rhc54 i think OMPI is fine indeed.
libevent global shutdown will be added into the embedded libevent in #2175
global shutdown will be only invoked by the embedded libevent glue. with the exception of pmix, no one else should be using the embedded libevent (e.g. user app should not use embedded libevent)

in OMPI, we could add an extra MCA param to invoke the global shutdown of the external libevent.
in PMIx, an environment variable could be used for that. in both case default is __not__ to shutdown libevent.
the rationale is it makes memory leak detection easier with valgrind and similar tools, for both OMPI apps and PMIx only apps.

does that make sense ?

**Comment by rhc54** [comment]
Looking at #2175 in OMPI - did you update libevent? If so, what version are you proposing to bring over? Last we checked, 2.0.22 is still the last stable release.

I'd have to think some more about the param for global shutdown. I don't immediately see the harm as it would be a conscious command from the user, and so the risk is theirs. Could be dicey if an OMPI user builds against an external libevent and PMIx, and then sets one or both of those envars. Seems like that would create a problem depending upon which one shut libevent down first.

**Comment by ggouaillardet** [comment]
i simply backported the commit from upstream libevent that adds the global shutdown, and updated the glue to invoke it.
