### ISSUE TITLE
PMIx_server_init() does not have information about jobid

### ISSUE THREAD

**Issue by igor-ivanov** [pmix/master#47]
Current version of the library does not require passing jobid to PMIx_server_init().
Is there easy way to get one inside PMIx_server_init? Should we require passing jobid to PMIx_server_init?

**Comment by artpol84** [comment]
@igor-ivanov 
We can use namespace here. It supposed to be unique among jobs running on the cluster and usually constructed using jobid.

**Comment by artpol84** [comment]
Here are my thoughts on this.
* We initialize dstore in `PMIx_server_init()`:
https://github.com/igor-ivanov/master/blob/pr/add-dstore/src/server/pmix_server.c#L312
at this point we have no knowledge about namespace(s) that will be hosted (we can use this info to create unique file names).
* The opportunity to use **this** server namespace (we can pass one through the `info` argument as we do with User ID now) has **major disadvantage** - lack of flexibility: one server may host **several groups** of processes inside **different namespaces**.
* So we need the value that is unique for **this** server and namespace is not the one.
* However server PID sounds like a reasonable solution here. `dstore` is binded to the particular server and makes sense only while it is running and in normal case client's lifetime can't exceed the servers lifetime. It is already used to provide uniqueness of the socket name.
* Server PID is accessible to the clients though `PMIX_SERVER_URI` env (unless `PMIX_SERVER_RANK` env was provided by RM):
https://github.com/igor-ivanov/master/blob/pr/add-dstore/src/server/pmix_server.c#L230:L235

@rhc54 can you comment on the purposes of `PMIX_SERVER_RANK`? Can we say that `PMIX_SERVER_RANK` is unique on the node at any point of time?

If answer is **yes** we can go ahead and use *server rank* as unique information to form the shared memory filenames.
If answer is **no** we can pass aditional env (`PMIX_SERVER_PID` ?) to the client that provides information about server PID. Because for the socket name we always use **PID** and not **rank**.

**Comment by rhc54** [comment]
PMIX_SERVER_RANK is certainly unique not only on the node, but across the entire allocation (and quite possibly the cluster, depending on how the RM implements the server). Because of shared file systems, the PID isn't a safe choice by itself. In OMPI, we protect the PID-based name of the server's connection socket by creating it underneath a session directory that is based on node name and server rank, and we would expect the shared memory segment to be in that same location (i.e., under the passed TMPDIR location).

**Comment by igor-ivanov** [comment]
move discussion to https://github.com/pmix/master/issues/46
